/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.ibara1454.effect

/**
 * [effect] allows you to make side-effects [action] with the result of given function [f].
 *
 * In general, [action] should not contain any business logic and should not throw exceptions.
 *
 * @param action any side-effect, e.g. make logs
 * @param f the function you actually want to call
 * @return which is same to the result of [f]
 */
inline fun <T> effect(action: (T) -> Unit, f: () -> T): T {
    // The identity function
    val id: (T) -> T = { x -> x }
    // Delegate to the overload function
    return effect(id, action, f)
}

/**
 * [effect] allows you to make side-effects [action] with the result of given function [f].
 *
 * In general, [action] should not contain any business logic and should not throw exceptions.
 *
 * @param transformer transforms the result of [f] and pass it to [action]
 * @param action any side-effect, e.g. make logs
 * @param f the function you actually want to call
 * @return which is same to the result of [f]
 */
inline fun <T, R> effect(transformer: (T) -> R, action: (R) -> Unit, f: () -> T): T {
    val result = f()
    action(transformer(result))
    return result
}
